# Generated by Django 4.0.4 on 2022-05-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_authors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='Review',
        ),
        migrations.AddField(
            model_name='review',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='book_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
