# Generated by Django 4.0.4 on 2022-05-07 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_review_book_id_alter_review_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='book_id',
            new_name='Book',
        ),
    ]
