# Generated by Django 4.0.4 on 2022-05-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_author_remove_book_authors_book_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
